from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/r32b_closeout'
def tab(d):
 d=d.head(12); c=list(d.columns); return '| '+' | '.join(c)+' |\n| '+' | '.join(['---']*len(c))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def wr(name,title,method,sample,df,rel):
 (ROOT/'reports'/name).write_text(f'# {title}\n\n## METHOD\n\n{method}\n\n## SAMPLE\n\n{sample}\n\n## NUMERICAL RESULTS\n\n{tab(df)}\n\n## UNCERTAINTY\n\nClustered folds and paired evaluation outputs are retained in canonical files.\n\n## INTERPRETATION\n\nThese are associative selected-sample estimates.\n\n## LIMITATIONS\n\nOutcome-dependent target/receiver missingness limits generalization.\n\n## PAPER RELEVANCE\n\n{rel}\n\n## CANONICAL FILES\n\n`results/r32b_closeout/`\n')
def main():
 m=pd.read_csv(R/'receiver_model_metrics.csv'); ci=pd.read_csv(R/'receiver_incremental_ci.csv'); c6=pd.read_parquet(R/'central_6_actions.parquet'); lg=pd.read_parquet(R/'long_target_actions.parquet'); rst=pd.read_csv(R/'restart_curve.csv'); pair=pd.read_csv(R/'pair_model_comparison.csv'); role=pd.read_csv(R/'receiver_role_coverage.csv')
 wr('R32B_CLOSEOUT_RECEIVERS.md','R3.2B receiver closeout','Corrected match-specific roles; identical match-grouped folds compare geometry, role, fold-safe residual profile, player identity and role-profile.','Selected target-identifiable actions only.',m,'Major secondary/supporting result.')
 wr('R32B_CLOSEOUT_CENTRAL_6.md','R3.2B central #6 closeout','Primary proxy requires DM_6, target_y 28–52, intended distance 10–35 m, target forward of origin and open-play GK distribution.','Proxy actions: '+str(len(c6)),pd.DataFrame([{'n':len(c6),'matches':c6.match_id.nunique(),'cohorts':c6.cohort.nunique(),'keepers':c6.keeper_id.nunique(),'receivers':c6.receiver_id.nunique(),'R1':c6.R1.mean(),'TA_GEO_xR':c6['p_TA-GEO'].mean(),'TA_ROLE_PROFILE_xR':c6['p_TA-ROLE-PROFILE'].mean()}]),'Practitioner extension.')
 wr('R32B_CLOSEOUT_LONG_TARGET.md','R3.2B long target-forward closeout','Primary proxy requires STRIKER and intended distance >=40 m, forward of origin; realized endpoint distance is excluded.','Proxy actions: '+str(len(lg)),pd.DataFrame([{'n':len(lg),'matches':lg.match_id.nunique(),'cohorts':lg.cohort.nunique(),'keepers':lg.keeper_id.nunique(),'receivers':lg.receiver_id.nunique(),'R1':lg.R1.mean(),'TA_GEO_xR':lg['p_TA-GEO'].mean(),'TA_ROLE_PROFILE_xR':lg['p_TA-ROLE-PROFILE'].mean()}]),'Practitioner extension.')
 wr('R32B_CLOSEOUT_RESTARTS.md','R3.2B restart closeout','Goal-kick primary analysis uses standardized intended target distance and a numeric spline curve; descriptive bands are predeclared.','Target-identifiable goal kicks.',rst,'Supporting/appendix result; the historical 40–60 m claim is evaluated, not assumed.')
 wr('R32B_CLOSEOUT_PAIR_EFFECT.md','R3.2B pair effect closeout','Regularized outer match-fold BASE and BASE+GK-receiver-pair models are fit on supported selected actions.','Known receiver selected sample.',pair,'Pair signal classification remains support-limited.')
 wr('R32B_CLOSEOUT_SCIENCE_LOCK.md','R3.2B science lock closeout','Receiver roles are now match-specific and populated; profile features enter the fitted numeric preprocessor; pair and restart models are separately fit.','Overall selected sample role coverage is reported in receiver_role_coverage.csv.',pd.concat([m,role],axis=1),'Final conclusion: intended geometry is primary; receiver type/profile add selected-sample information, while identity, pair effects and tactical option-set claims remain limited. Tracking/360 is required for available-option choice.')
if __name__=='__main__':main()
