from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/r32b'
def tab(d):
 d=d.head(12); cols=list(d.columns); return '| '+' | '.join(cols)+' |\n| '+' | '.join(['---']*len(cols))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def write(name,title,method,sample,df,rel):
 (ROOT/'reports'/name).write_text(f'# {title}\n\n## METHOD\n\n{method}\n\n## SAMPLE\n\n{sample}\n\n## NUMERICAL RESULTS\n\n{tab(df)}\n\n## UNCERTAINTY\n\nMatch-grouped folds and cluster bootstrap results are retained in the canonical CSV files.\n\n## INTERPRETATION\n\nResults are associative and restricted to the target-identifiable selected sample.\n\n## LIMITATIONS\n\nTarget/receiver missingness is outcome-dependent; these findings do not generalize to all goalkeeper distributions.\n\n## PAPER RELEVANCE\n\n{rel}\n\n## CANONICAL FILES\n\n`results/r32b/`\n')
def main():
 m=pd.read_csv(R/'receiver_model_metrics.csv'); a=pd.read_csv(R/'receiver_availability.csv').head(10); ci=pd.read_csv(R/'receiver_incremental_ci.csv'); adj=pd.read_csv(R/'gk_receiver_adjustment.csv').head(10); pair=pd.read_csv(R/'pair_model_comparison.csv'); c6=pd.read_csv(R/'central_6_proxy_results.csv'); long=pd.read_csv(R/'long_target_proxy_results.csv'); rst=pd.read_csv(R/'restart_intended_distance.csv')
 write('R32B_RECEIVER_MODEL.md','R3.2B receiver model','TA-GEO, TA-ROLE, TA-PROFILE, TA-PLAYER and TA-ROLE-PROFILE use identical match-grouped folds on target-identifiable actions.','Selected TA actions only.',m,'Receiver role/profile is a major secondary result; player identity remains appendix evidence.')
 write('R32B_RECEIVER_GENERALIZATION.md','R3.2B receiver generalization','Known-receiver folds, unseen-receiver folds and unseen-team receiver predictions are kept distinct.','Held-out match, receiver and team groups.',pd.concat([m,ci.head(10)],axis=1),'Generalization is supporting evidence with selected-sample limits.')
 write('R32B_GK_RECEIVER_CREDIT.md','R3.2B goalkeeper receiver adjustment','OOF geometry and receiver-conditioned expectations are compared within cohort with shrinkage.','Keeper aggregates on selected actions.',adj,'Associative goalkeeper evaluation only; no causal receiver credit.')
 write('R32B_PAIR_EFFECT.md','R3.2B pair effect','Pair summaries require prior history and are compared against receiver-conditioned models.','Keeper-receiver pairs with support flags.',pair,'Pair effect is not supported as a distinct repeatable signal.')
 write('R32B_CENTRAL_6_PROXY.md','R3.2B central #6 target proxy','Primary proxy requires receiver_role == DM_6, central target corridor and intended distance 10–45 m; it is not a confirmed checking movement.','Target-identifiable DM_6 actions.',c6,'Practitioner extension; tracking is required for checking movement.')
 write('R32B_LONG_TARGET_FORWARD.md','R3.2B long target-forward proxy','Primary proxy requires receiver_role == STRIKER and intended distance >=40 m in target zones.','Target-identifiable long STRIKER actions.',long,'Practitioner extension; do not call a player a target man solely from these events.')
 write('R32B_RESTARTS.md','R3.2B corrected restarts','Primary restart analysis uses intended target distance; realized distance is retrospective descriptive only.','Goal-kick/restart actions.',rst,'Appendix/supporting result; historical 40–60 m claim remains disabled.')
 write('R32B_TRACKING_FUTURE.md','R3.2B tracking boundary','Event data do not observe the full receiver option set. A future 360/tracking model must score every feasible receiver/action j by xR, success value, failure consequence and expected action value.','Option-set counterfactual is not estimable here.',a,'Future work.')
 write('R32B_SCIENCE_LOCK.md','R3.2B science lock','Four primary questions are answered with selected-sample match-safe analyses and explicit receiver/restart proxies.','Receiver availability, models, generalization, pair, #6, long-target and restart outputs.',m,'Final thesis: intended geometry is primary; receiver type/profile adds selected-sample information, while identity, pair effects and tactical counterfactuals remain limited. Context is a major secondary result.')
if __name__=='__main__':main()
