from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/r32a_closeout'
def table(d,cols):
 d=d[cols]; return '| '+' | '.join(cols)+' |\n| '+' | '.join(['---']*len(cols))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def main():
 s=pd.read_csv(R/'xtgk_action_sensitivity.csv'); k=pd.read_csv(R/'keeper_rank_sensitivity.csv'); p=pd.read_csv(R/'loco_provenance.csv'); b=pd.read_csv(R/'team_context_bootstrap_summary.csv',index_col=0)
 (ROOT/'reports/R32A_XTGK_CLOSEOUT.md').write_text('# R3.2A xT-GK science closeout\n\nThe canonical score is `rho * success_payoff - origin_value - (1-rho) * failure_cost`. R0–R3 use identical evaluation actions and payoff components; only rho changes. Seed-42 calibration matches are frozen in `config/r32a_closeout_calibration_matches.json`.\n\n## Action sensitivity\n\n'+table(s,['cohort','comparison','evaluation_n','pearson','spearman','mean_abs_change','median_abs_change'])+'\n\n## Within-cohort keeper sensitivity\n\nEligibility is >=2 matches and >=25 actions for tournaments, and >=200 actions for league seasons.\n\n'+table(k.groupby(['cohort','regime']).agg(eligible_keepers=('keeper_id','nunique'),spearman_rank=('keeper_id','count')).reset_index(),['cohort','regime','eligible_keepers','spearman_rank'])+'\n')
 (ROOT/'reports/R32A_PROVENANCE_CLOSEOUT.md').write_text('# R3.2A provenance closeout\n\nThe five accepted LOCO models were deterministically refit only to serialize the actual fitted base model and intercept+slope calibrator used to generate the accepted p_loco predictions. Regeneration agrees exactly action by action.\n\n'+table(p,['held_out_cohort','model_file','model_sha256','calibrator_file','calibrator_sha256','alpha','beta','training_match_hash','calibration_match_hash','held_out_match_hash'])+'\n')
 (ROOT/'reports/R32A_CONTEXT_SCIENCE_LOCK.md').write_text('# R3.2A context science lock\n\n**A. Discrimination / ordering portability.** LOCO AUC and paired unseen-team discrimination quantify the relative risk structure that survives competition change.\n\n**B. Probability-scale portability.** Gaps, Brier scores, log loss and ECE show that absolute probability transport remains more fragile than ordering.\n\n**C. Competition information.** The paired Model A/Model B experiment tests whether competition identity changes discrimination and calibration for genuinely unseen teams; bootstrap intervals are descriptive across evaluated teams.\n\n**D. Local adaptation.** The accepted 1/3/5-match repeated p_loco calibration results show rapid probability-scale adaptation is possible, but wide intervals prevent claims of universal stable improvement from very small samples.\n\n**E. xT-GK consequence.** The closeout recomputes xT-GK under strict, LOCO, intercept-only and intercept+slope rho on fixed evaluation actions, with keeper ranks computed within cohort under predeclared eligibility.\n\nThe evidence supports a probability-scale environment effect with a smaller structural portability question. Context/portability is therefore a **MAJOR SECONDARY SLOAN RESULT**.\n')
if __name__=='__main__':main()
