from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/r32a_patch'
def table(d,cols):
 d=d[cols]; return '| '+' | '.join(cols)+' |\n| '+' | '.join(['---']*len(cols))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def main():
 z=pd.read_csv(R/'loco_zero_shot.csv'); s=pd.read_csv(R/'loco_local_calibration_summary.csv'); t=pd.read_csv(R/'unseen_team_competition_metrics.csv'); x=pd.read_csv(R/'xtgk_patch_propagation.csv'); k=pd.read_csv(R/'xtgk_patch_keeper_rank_shifts.csv')
 (ROOT/'reports/R32A_PATCH_CALIBRATION.md').write_text('# R3.2A Patch 1 calibration\n\n## Table 1 — five zero-shot LOCO cohorts\n\n'+table(z,['cohort','n','gap','brier','log_loss','ece','auc'])+'\n\n## Table 2 — local calibration summaries\n\nEach row is a median and 2.5%/97.5% interval over 100 feasible repeated match draws. Both methods calibrate p_loco.\n\n'+table(s,['cohort','method','calibration_matches','repeats','gap_median','gap_lo','gap_hi','brier_median','brier_lo','brier_hi','log_loss_median','ece_median','auc_median'])+'\n')
 (ROOT/'reports/R32A_PATCH_TEAM_CONTEXT.md').write_text('# R3.2A Patch 1 unseen-team competition context\n\nModel A is the approved structural TF model. Model B adds competition/cohort identity while excluding held-out team actions from training.\n\n'+table(t,['held_out_team_id','held_out_team_name','AUC_A','AUC_B','delta_AUC','Brier_A','Brier_B','delta_Brier','log_loss_A','log_loss_B','ECE_A','ECE_B','gap_A','gap_B'])+'\n\nThe paired distribution summary is in `results/r32a_patch/unseen_team_competition_summary.csv`.\n')
 (ROOT/'reports/R32A_PATCH_XTGK.md').write_text('# R3.2A Patch 1 xT-GK propagation\n\nEach cohort uses a fixed seed-42 five-match local calibration split where feasible; all remaining actions are evaluation actions. R0 is frozen strict TF, R1 zero-shot LOCO, R2 LOCO plus canonical intercept-only calibration, and R3 LOCO plus intercept+slope calibration. Keeper ranks are computed within cohort only.\n\n'+table(x,['cohort','comparison','evaluation_n','pearson','spearman','mean_abs_value_change'])+'\n\nRank shifts are in `xtgk_patch_keeper_rank_shifts.csv`; action values are in `xtgk_patch_action_values.parquet`.\n')
 (ROOT/'reports/R32A_PATCH_DECISION.md').write_text('# R3.2A Patch 1 decision\n\n1. Structural TF risk generalizes to unseen competitions with measurable probability-scale transport error; the five-row zero-shot table is canonical.\n2. Broad heterogeneous training reduces but does not remove the need for local calibration.\n3. The repeated 1/3/5-match p_loco learning curves quantify how quickly adaptation improves.\n4. Competition identity is tested directly with paired unseen-team Model A versus Model B results.\n5. xT-GK action values are recomputed under all four probability regimes on identical evaluation actions.\n6. Keeper rank changes are measured within cohorts, with no cross-cohort ranking.\n7. The primary football-environment effect is probability-scale, with structural effects assessed as secondary.\n8. Context/portability should remain a major secondary Sloan result.\n')
if __name__=='__main__':main()
