from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/r32a_final'
def table(df, cols):
    d=df[cols].head(15); return '| '+' | '.join(cols)+' |\n| '+' | '.join(['---']*len(cols))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def main():
    loco=pd.read_csv(R/'loco_metrics.csv'); team=pd.read_csv(R/'unseen_team_metrics.csv'); xt=pd.read_csv(R/'xtgk_propagation_metrics.csv')
    (ROOT/'reports/R32A_FINAL_LOCO.md').write_text('# R3.2A final LOCO experiment\n\n## METHOD\n\nEach cohort is fully held out. Other cohorts are split by match into base training and calibration.\n\n## RESULTS\n\n'+table(loco,['held_out_cohort','n','prevalence','mean_prediction','gap','auc','pr_auc','brier','log_loss','ece'])+'\n\n## UNCERTAINTY AND LIMITATIONS\n\nLocal calibration repeats are in `loco_local_calibration.csv`; provenance hashes are in `loco_provenance.csv`. These are TF release-context estimates, not transfer forecasts.\n\n## CANONICAL FILES\n\n`loco_predictions.parquet`, `loco_metrics.csv`, `loco_local_calibration.csv`, `loco_provenance.csv`.\n')
    (ROOT/'reports/R32A_FINAL_TEAM_PORTABILITY.md').write_text('# R3.2A final team portability experiment\n\n## METHOD\n\nTeams with at least 250 eligible actions are held out one at a time; team identity is excluded.\n\n## RESULTS\n\n'+table(team,['held_out_team_id','n','prevalence','mean_prediction','gap','auc','pr_auc','brier','log_loss','ece'])+'\n\n## UNCERTAINTY AND LIMITATIONS\n\nThe distribution is summarized in `unseen_team_summary.csv`. Open event data do not fully describe team game models.\n\n## CANONICAL FILES\n\n`unseen_team_predictions.parquet`, `unseen_team_metrics.csv`, `unseen_team_summary.csv`, `unseen_team_provenance.csv`.\n')
    (ROOT/'reports/R32A_FINAL_XTGK_PROPAGATION.md').write_text('# R3.2A final xT-GK propagation experiment\n\n## METHOD\n\nThe same action set, success payoff, failure cost and kappa are used; only rho changes.\n\n## RESULTS\n\n'+table(xt,['cohort','comparison','pearson','spearman','mean_abs_value_change'])+'\n\n## UNCERTAINTY AND LIMITATIONS\n\nKeeper rank movement is in `xtgk_keeper_rank_changes.csv` with a minimum 100-action filter.\n\n## CANONICAL FILES\n\n`xtgk_action_values.parquet`, `xtgk_propagation_metrics.csv`, `xtgk_keeper_rank_changes.csv`.\n')
    (ROOT/'reports/R32A_FINAL_DECISION.md').write_text('# R3.2A final decision\n\n1. LOCO portability is determined from `loco_metrics.csv`.\n2. TF generalization to unseen teams is measured in `unseen_team_metrics.csv`.\n3. Competition knowledge is separated from held-out team identity.\n4. Local calibration remains necessary where prevalence and slope drift.\n5. xT-GK action values and keeper rank changes are recomputed under true LOCO rho.\n6. Probability-scale drift is established more clearly than structural portability.\n7. Context/portability belongs as a major secondary result.\n8. Canonical files: `loco_metrics.csv`, `unseen_team_metrics.csv`, `xtgk_propagation_metrics.csv`.\n')
if __name__=='__main__': main()
