from pathlib import Path
import pandas as pd, json
ROOT=Path(__file__).resolve().parents[1]; R=ROOT/'results/final_evidence_v2'
def t(d):
 d=d.head(15); c=list(d.columns); return '| '+' | '.join(c)+' |\n| '+' | '.join(['---']*len(c))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in d.itertuples(index=False,name=None))
def main():
 tf=pd.read_csv(R/'tf_ta_geo_by_cohort.csv'); dc=pd.read_csv(R/'deep_consequence_summary.csv'); ctx=pd.read_csv(R/'context_final.csv'); rep=pd.read_csv(R/'repeatability_final.csv'); rec=pd.read_csv(R/'receiver_supporting_final.csv'); dead=pd.DataFrame([['completion inversion','old negative correlations','not a valid universal claim','FAIL'],['universal 40–60 m','old restart claim','disabled','FAIL'],['style-neutrality','historical claim','unsupported','FAIL'],['causal transfer success','transfer claim','unsupported','FAIL'],['receiver profile positive result','profile claim','quarantined','FAIL']],columns=['claim','old','new','status'])
 text='# FINAL SLOAN EVIDENCE LOCK V2\n\n## Executive verdict\n\nThe single central contribution is asymmetric two-branch ex-ante goalkeeper distribution valuation. Four major empirical results are retained: replicated deep failure consequence, qualified relative-risk portability, intended geometry improvement on the selected sample, and environment-dependent probability/xT adaptation.\n\n## Central conceptual contribution\n\nValue = retention probability × retained-action payoff − failure probability × failure consequence, with origin value surrendered in both branches.\n\n## Deep consequence table\n\n'+t(dc)+'\n\n## Intended-target table\n\nIntended targets are outcome-dependently observed; these are selected-sample comparisons.\n\n'+t(tf)+'\n\n## Portability/context\n\n'+t(ctx)+'\n\n## xT adaptation\n\nAccepted R3.2A closeout outputs show probability/model choice can alter action valuation and within-cohort keeper ordering.\n\n## Completion and repeatability\n\nCompletion alone is insufficient to value distribution. Repeatability is reported for completion, R1, TF rho, TF residual, TA-GEO rho and TA residual using deterministic alternating match splits; residual execution is not promoted to stable skill.\n\n'+t(rep)+'\n\n## Supporting receiver evidence\n\n'+t(rec)+'\n\n## Claims that failed\n\n'+t(dead)+'\n\n## Limitations and tracking/360\n\nReceiver evidence is selected-sample only. Option sets, checking movement and best-available-receiver choice require tracking/360.\n\n## Figure plan\n\n'+t(pd.read_csv(R/'figure_plan.csv'))+'\n\n## Abstract fact set\n\n'+t(pd.DataFrame(json.load(open(R/'abstract_fact_set.json'))))+'\n\n## Exact scientific thesis\n\nGoalkeeper distribution should be valued as an asymmetric ex-ante expectation. Deep failure consequences replicate across cohorts, relative risk transports better than absolute probabilities, and intended geometry improves selected-sample estimation; local calibration affects valuation.\n\n## DO-NOT-USE\n\nDo not use receiver profile, #6, long-target, pair, universal 40–60 m, style-neutrality, completion-inversion, or causal transfer-success claims as positive main-paper evidence.\n'
 (ROOT/'reports/FINAL_SLOAN_EVIDENCE_LOCK_V2.md').write_text(text)
if __name__=='__main__':main()
